/** Shared i18n labels */
export const labels = {
  startExam: { de: "Prüfung starten", en: "Start Exam" },
  finishExam: { de: "Prüfung abschließen", en: "Finish Exam" },
  nextQuestion: { de: "Nächste Frage", en: "Next Question" },
  prevQuestion: { de: "Vorherige Frage", en: "Previous Question" },
  question: { de: "Frage", en: "Question" },
  of: { de: "von", en: "of" },
  points: { de: "Punkte", en: "Points" },
  point: { de: "Punkt", en: "Point" },
  results: { de: "Ergebnisse", en: "Results" },
  passed: { de: "Bestanden! 🎉", en: "Passed! 🎉" },
  failed: { de: "Nicht bestanden", en: "Not Passed" },
  totalScore: { de: "Gesamtpunktzahl", en: "Total Score" },
  passThreshold: { de: "Bestehensgrenze", en: "Pass Threshold" },
  yourScore: { de: "Dein Ergebnis", en: "Your Score" },
  backToStart: { de: "Zurück zum Start", en: "Back to Start" },
  retryExam: { de: "Erneut versuchen", en: "Retry Exam" },
  questionsReview: { de: "Fragenübersicht", en: "Questions Review" },
  correct: { de: "Richtig", en: "Correct" },
  incorrect: { de: "Falsch", en: "Incorrect" },
  partiallyCorrect: { de: "Teilweise richtig", en: "Partially Correct" },
  yourAnswer: { de: "Deine Antwort", en: "Your Answer" },
  correctAnswer: { de: "Richtige Antwort", en: "Correct Answer" },
  explanation: { de: "Erklärung", en: "Explanation" },
  selected: { de: "ausgewählt", en: "selected" },
  required: { de: "erforderlich", en: "required" },
  tooFew: { de: "Zu wenig ausgewählt", en: "Too few selected" },
  tooMany: { de: "Zu viele ausgewählt", en: "Too many selected" },
  correctCount: { de: "Richtige Anzahl", en: "Correct count" },
  examTitle: { de: "iSAQB CPSA-F Probeprüfung", en: "iSAQB CPSA-F Mock Exam" },
  examSubtitle: {
    de: "Certified Professional for Software Architecture — Foundation Level",
    en: "Certified Professional for Software Architecture — Foundation Level",
  },
  examDescription: {
    de: "Teste dein Wissen mit der inoffiziellen iSAQB-Probeprüfung. Die Fragen stammen aus dem offiziellen iSAQB Foundation Level Fragenkatalog.",
    en: "Test your knowledge with the inofficial iSAQB mock exam. Questions are sourced from the official iSAQB Foundation Level question catalog.",
  },
  totalQuestions: { de: "Fragen", en: "Questions" },
  totalPoints: { de: "Gesamtpunkte", en: "Total Points" },
  passAt: { de: "Bestehen ab", en: "Pass at" },
  dataSourceLive: {
    de: "Aktuelle Fragen von GitHub",
    en: "Live questions from GitHub",
  },
  dataSourceFallback: {
    de: "Gebündelte Fragen (Offline)",
    en: "Bundled questions (Offline)",
  },
  dataSourceCached: {
    de: "Zwischengespeicherte Fragen",
    en: "Cached questions",
  },
  lastFetched: { de: "Zuletzt abgerufen", en: "Last fetched" },
  refetch: { de: "Neu laden", en: "Refresh" },
  questionsRateLimited: {
    de: "GitHub-API-Limit erreicht — in einem gemeinsamen Netzwerk (z.B. Workshop) wird das Limit schneller verbraucht. Es werden zwischengespeicherte bzw. gebündelte Fragen angezeigt. Versuche es in ca. einer Stunde erneut oder nutze mobile Daten.",
    en: "GitHub API rate limit reached — in a shared network (e.g. workshop), the limit is consumed faster. Showing cached or bundled questions. Try again in about an hour or use mobile data.",
  },
  scoringTitle: { de: "Bewertung", en: "Scoring" },
  scoringToggle: { de: "Wie wird bewertet?", en: "How is scoring calculated?" },
  scoringCorrectTitle: { de: "Richtig", en: "Correct" },
  scoringCorrectDesc: { de: "Anteilige Punkte", en: "Proportional points" },
  scoringWrongTitle: { de: "Falsch", en: "Wrong" },
  scoringWrongDesc: { de: "Punktabzug", en: "Deducts points" },
  scoringFloorTitle: { de: "Minimum", en: "Floor" },
  scoringFloorDesc: { de: "Nie unter 0", en: "Never below 0" },
  scoringOverTitle: { de: "Zu viele", en: "Over-select" },
  scoringOverDesc: { de: "Ergibt 0 Punkte", en: "Results in 0" },
  assignToCategory: { de: "Kategorie zuordnen:", en: "Assign to category:" },
  noAssignment: { de: "Keine Zuordnung", en: "No assignment" },
  skipToContent: { de: "Zum Inhalt springen", en: "Skip to content" },
  keyboardHints: {
    de: "Tastaturkürzel: ← → zum Navigieren, 1-9 für Optionen",
    en: "Keyboard: ← → to navigate, 1-9 for options",
  },
  learnMore: { de: "Mehr erfahren", en: "Learn more" },
  timeTaken: { de: "Benötigte Zeit", en: "Time Taken" },
  timePerQuestion: { de: "Zeitverteilung", en: "Time per Question" },
  timePerQuestionHint: {
    de: "Fragen, die länger gedauert haben, deuten auf Themen hin, die du nochmals wiederholen solltest.",
    en: "Questions that took longer may indicate topics worth revisiting.",
  },
  disclaimer: {
    de: "Dieses Tool und sein Autor sind nicht mit der iSAQB e.V. verbunden.\nEs wird keine Gewähr für die Richtigkeit der Fragen oder des Tests selbst übernommen.",
    en: "This tool and its author are not affiliated with iSAQB e.V.\nNo guarantee is provided for the correctness of the questions or the test itself.",
  },
  analyticsTitle: {
    de: "Datenschutzfreundliche Analysen",
    en: "Privacy-Friendly Analytics",
  },
  analyticsDescription: {
    de: "Diese Seite nutzt Umami, um anonyme Nutzungsstatistiken zu erheben.\nErfasst werden: Seitenaufrufe, Referrer, Browser, Betriebssystem, Gerätetyp und Land.\nEs werden keine Cookies gesetzt, keine persönlichen Daten gespeichert und kein Tracking über Seiten hinweg durchgeführt.",
    en: "This site uses Umami to collect anonymous usage statistics.\nCollected: page views, referrers, browser, OS, device type, and country.\nNo cookies are set, no personal data is stored, and no cross-site tracking is performed.",
  },
  exportResults: { de: "Drucken", en: "Print" },
  continueExam: { de: "Fortsetzen", en: "Continue" },
  newExam: { de: "Neue Prüfung", en: "New Exam" },
  savedExamTitle: { de: "Gespeicherte Prüfung", en: "Saved Exam" },
  savedExamProgress: { de: "Fragen beantwortet", en: "questions answered" },
  viewResults: { de: "Ergebnisse ansehen", en: "View Results" },
  savedExamFinished: { de: "Prüfung abgeschlossen", en: "Exam completed" },
  flagQuestion: { de: "Markieren", en: "Flag" },
  unflagQuestion: { de: "Markierung entfernen", en: "Unflag" },
  flaggedQuestionsTitle: { de: "Markierte Fragen", en: "Flagged Questions" },
  flaggedQuestionsBody: {
    de: "Du hast noch markierte Fragen zur Überprüfung. Möchtest du die Prüfung trotzdem abschließen?",
    en: "You still have flagged questions to review. Do you want to finish the exam anyway?",
  },
  finishAnyway: { de: "Trotzdem abschließen", en: "Finish Anyway" },
  reviewFlagged: { de: "Überprüfen", en: "Review" },
  unansweredQuestionsTitle: {
    de: "Unbeantwortete Fragen",
    en: "Unanswered Questions",
  },
  unansweredQuestionsBody: {
    de: "Du hast noch unbeantwortete Fragen. Möchtest du die Prüfung trotzdem abschließen?",
    en: "You still have unanswered questions. Do you want to finish the exam anyway?",
  },
  noteLabel: { de: "Notizen", en: "Notes" },
  notePlaceholder: {
    de: "Notizen für den Dozenten…",
    en: "Notes for the lecturer…",
  },
  noteForLecturer: {
    de: "Notiz für den Dozenten",
    en: "Note for the lecturer",
  },
  // Leaderboard
  leaderboard: { de: "Bestenliste", en: "Leaderboard" },
  leaderboardEmpty: {
    de: "Noch keine Einträge vorhanden.",
    en: "No entries yet.",
  },
  leaderboardError: {
    de: "Bestenliste konnte nicht geladen werden. In einem gemeinsamen Netzwerk (z.B. Workshop) kann das GitHub-API-Limit schnell erreicht werden. Versuche es in ca. einer Stunde erneut oder nutze mobile Daten.",
    en: "Could not load the leaderboard. In a shared network (e.g. workshop), the GitHub API limit can be reached quickly. Try again in about an hour or use mobile data.",
  },
  leaderboardLoading: {
    de: "Bestenliste wird geladen…",
    en: "Loading leaderboard…",
  },
  submitToLeaderboard: { de: "Ergebnis senden", en: "Submit Result" },
  viewLeaderboard: { de: "Bestenliste ansehen", en: "View Leaderboard" },
  leaderboardRank: { de: "#", en: "#" },
  leaderboardUser: { de: "Benutzer", en: "User" },
  leaderboardScore: { de: "Punkte", en: "Score" },
  leaderboardPercentage: { de: "Prozent", en: "Percentage" },
  leaderboardTime: { de: "Zeit", en: "Time" },
  leaderboardDate: { de: "Datum", en: "Date" },
  leaderboardPassedBadge: { de: "Bestanden", en: "Passed" },
  leaderboardFailedBadge: { de: "Nicht bestanden", en: "Failed" },
  leaderboardSubmitInfo: {
    de: "Dein Ergebnis wird über ein GitHub Issue eingereicht und automatisch verifiziert.",
    en: "Your result is submitted via a GitHub Issue and verified automatically.",
  },
  leaderboardOfflineWarning: {
    de: "Die Bestenliste ist nur mit Online-Fragen verfügbar (nicht mit Offline-/Fallback-Fragen).",
    en: "Leaderboard submission is only available with online questions (not offline/fallback).",
  },
  leaderboardRateLimited: {
    de: "GitHub-API-Limit erreicht — in einem gemeinsamen Netzwerk (z.B. Workshop) wird das Limit schneller verbraucht. Es werden zwischengespeicherte Daten angezeigt. Versuche es in ca. einer Stunde erneut oder nutze mobile Daten.",
    en: "GitHub API rate limit reached — in a shared network (e.g. workshop), the limit is consumed faster. Showing cached data. Try again in about an hour or use mobile data.",
  },
  leaderboardMaxEntries: {
    de: "Es werden maximal die letzten 1.000 Einträge angezeigt.",
    en: "Showing up to the last 1,000 entries.",
  },
} as const;
