/** Shared i18n labels */
export const labels = {
  startExam: { de: "Prüfung starten", en: "Start Exam" },
  finishExam: { de: "Prüfung abschließen", en: "Finish Exam" },
  nextQuestion: { de: "Nächste Frage", en: "Next Question" },
  prevQuestion: { de: "Vorherige Frage", en: "Previous Question" },
  question: { de: "Frage", en: "Question" },
  of: { de: "von", en: "of" },
  points: { de: "Punkte", en: "Points" },
  point: { de: "Punkt", en: "Point" },
  results: { de: "Ergebnisse", en: "Results" },
  passed: { de: "Bestanden! 🎉", en: "Passed! 🎉" },
  failed: { de: "Nicht bestanden", en: "Not Passed" },
  totalScore: { de: "Gesamtpunktzahl", en: "Total Score" },
  passThreshold: { de: "Bestehensgrenze", en: "Pass Threshold" },
  yourScore: { de: "Dein Ergebnis", en: "Your Score" },
  backToStart: { de: "Zurück zum Start", en: "Back to Start" },
  retryExam: { de: "Erneut versuchen", en: "Retry Exam" },
  questionsReview: { de: "Fragenübersicht", en: "Questions Review" },
  correct: { de: "Richtig", en: "Correct" },
  incorrect: { de: "Falsch", en: "Incorrect" },
  partiallyCorrect: { de: "Teilweise richtig", en: "Partially Correct" },
  yourAnswer: { de: "Deine Antwort", en: "Your Answer" },
  correctAnswer: { de: "Richtige Antwort", en: "Correct Answer" },
  explanation: { de: "Erklärung", en: "Explanation" },
  selected: { de: "ausgewählt", en: "selected" },
  required: { de: "erforderlich", en: "required" },
  tooFew: { de: "Zu wenig ausgewählt", en: "Too few selected" },
  tooMany: { de: "Zu viele ausgewählt", en: "Too many selected" },
  correctCount: { de: "Richtige Anzahl", en: "Correct count" },
  examTitle: { de: "iSAQB CPSA-F Probeprüfung", en: "iSAQB CPSA-F Mock Exam" },
  examSubtitle: {
    de: "Certified Professional for Software Architecture — Foundation Level",
    en: "Certified Professional for Software Architecture — Foundation Level",
  },
  examDescription: {
    de: "Teste dein Wissen mit der offiziellen iSAQB-Probeprüfung. Die Fragen stammen aus dem offiziellen iSAQB Foundation Level Fragenkatalog.",
    en: "Test your knowledge with the official iSAQB mock exam. Questions are sourced from the official iSAQB Foundation Level question catalog.",
  },
  totalQuestions: { de: "Fragen", en: "Questions" },
  totalPoints: { de: "Gesamtpunkte", en: "Total Points" },
  passAt: { de: "Bestehen ab", en: "Pass at" },
  dataSourceLive: {
    de: "Aktuelle Fragen von GitHub",
    en: "Live questions from GitHub",
  },
  dataSourceFallback: {
    de: "Gebündelte Fragen (Offline)",
    en: "Bundled questions (Offline)",
  },
  dataSourceCached: {
    de: "Zwischengespeicherte Fragen",
    en: "Cached questions",
  },
  lastFetched: { de: "Zuletzt abgerufen", en: "Last fetched" },
  refetch: { de: "Neu laden", en: "Refresh" },
  scoringInfo: {
    de: "Bewertung: Für jede richtige Auswahl gibt es anteilige Punkte, für jede falsche Auswahl werden anteilige Punkte abgezogen. Minimum 0 Punkte pro Frage. Werden mehr Optionen gewählt als richtige Antworten vorhanden sind, ergibt das immer 0 Punkte.",
    en: "Scoring: Each correct selection earns proportional points, each incorrect selection deducts proportional points. Minimum 0 points per question. Selecting more options than correct answers always results in 0 points.",
  },
  assignToCategory: { de: "Kategorie zuordnen:", en: "Assign to category:" },
  noAssignment: { de: "Keine Zuordnung", en: "No assignment" },
  skipToContent: { de: "Zum Inhalt springen", en: "Skip to content" },
  keyboardHints: {
    de: "Tastaturkürzel: ← → zum Navigieren, 1-9 für Optionen",
    en: "Keyboard: ← → to navigate, 1-9 for options",
  },
  learnMore: { de: "Mehr erfahren", en: "Learn more" },
  timeTaken: { de: "Benötigte Zeit", en: "Time Taken" },
  timePerQuestion: { de: "Zeitverteilung", en: "Time per Question" },
  disclaimer: {
    de: "Dieses Tool und sein Autor sind nicht mit der iSAQB e.V. verbunden.\nEs wird keine Gewähr für die Richtigkeit der Fragen oder des Tests selbst übernommen.\nDiese Seite verwendet datenschutzfreundliche, cookielose Analysen mit Umami.",
    en: "This tool and its author are not affiliated with iSAQB e.V.\nNo guarantee is provided for the correctness of the questions or the test itself.\nThis site uses privacy-friendly, cookie-less analytics with Umami.",
  },
  exportResults: { de: "Drucken", en: "Print" },
  continueExam: { de: "Fortsetzen", en: "Continue" },
  newExam: { de: "Neue Prüfung", en: "New Exam" },
  savedExamTitle: { de: "Gespeicherte Prüfung", en: "Saved Exam" },
  savedExamProgress: { de: "Fragen beantwortet", en: "questions answered" },
  viewResults: { de: "Ergebnisse ansehen", en: "View Results" },
  savedExamFinished: { de: "Prüfung abgeschlossen", en: "Exam completed" },
} as const;
